### PR TITLE
fixed a timeout bug.

### PR DESCRIPTION
**Pull request by kadupitiya**
@jadhao: fixed a timeout bug. I tested this with 500 jobs in 6 different severs. Please accept.

### CODE REVIEW

**Review by jadhao — APPROVED** [review]
@kadupitiya approving

**Comment by jadhao** [comment]
@kadupitiya was wondering if the README page is sufficient. as a demo, say if I want to use this functionality, could we have a more detailed readme that enables me to use this seamlessly?

**Comment by jadhao** [comment]
@kadupitiya you have write permission

**Comment by kadupitiya** [comment]
@jadhao: I updated the readme file. Please let me know if that is acceptable.

**Pull request merged**
